### ISSUE TITLE
logo link bo'lish kerak

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [AbdunazarovM/Classic#6]
![Screenshot_1](https://user-images.githubusercontent.com/77617034/116656470-2c6df100-a9a6-11eb-85cc-695ee4b2cb38.png)
tepadagi va pastdagi logo lar link bo'lishi kerak. masterklassda aytilgan

**Comment by AbdunazarovM** [comment]
link o'zi menda ham shunchaki href ni o'chirib tashlaganman

**Comment by ShokhrukhTurgunov** [comment]
yoqib qo'yish kerak

**Comment by AbdunazarovM** [comment]
ok :ok:
