### ISSUE TITLE
button cursor pointer bo'lgani yaxshi

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [AbdunazarovM/Classic#7]
![Screenshot_3](https://user-images.githubusercontent.com/77617034/116656568-54f5eb00-a9a6-11eb-88bc-240ad0fb4d62.png)
shu button lar cursor pointer bo'lgani yaxshi. bosiladigan narsa ekanligi bilinib turishi kerak

**Comment by AbdunazarovM** [comment]
fixed
