### ISSUE TITLE
pizza item title link bo'lgani yaxshi

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [AbdunazarovM/Classic#8]
![Screenshot_4](https://user-images.githubusercontent.com/77617034/116656782-b453fb00-a9a6-11eb-9762-a01b1cb87e2e.png)
mana shu title lar link bo'lsa yaxshi menimcha. sizda faqat pastdagi savatcha button bo'lgan xolos, foydalanuvchi zakaz berishga qiynalishi mumkin

**Comment by AbdunazarovM** [comment]
okay qilindi akam
